// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: cctranfer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CCTransfer struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Id     string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // unique transfer id
	From   string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`     // channel from
	To     string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`         // channel to
	Token  string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`   // transfer token (deprecated)
	User   []byte                 `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`     // token holder (deprecated)
	Amount []byte                 `protobuf:"bytes,6,opt,name=amount,proto3" json:"amount,omitempty"` // number of tokens (deprecated)
	// Transfer direction is an additional variable made for convenience
	// so that you don't have to calculate it every time. It is calculated 1 time when filling the structure
	// when executing a transaction.
	// Different balances change depending on the direction.
	// Examples:
	// Direct transfer: we transfer A tokens from channel A to channel B
	// or transfer B tokens from channel B to channel A
	// Reverse transfer:from channel A to channel B transfer tokens B
	// or from channel B to channel A transfer tokens A
	ForwardDirection bool              `protobuf:"varint,7,opt,name=forward_direction,json=forwardDirection,proto3" json:"forward_direction,omitempty"`
	IsCommit         bool              `protobuf:"varint,8,opt,name=isCommit,proto3" json:"isCommit,omitempty"`                            // phase 2 sign
	TimeAsNanos      int64             `protobuf:"varint,9,opt,name=time_as_nanos,json=timeAsNanos,proto3" json:"time_as_nanos,omitempty"` // transfer creation time in nanoseconds
	Items            []*CCTransferItem `protobuf:"bytes,10,rep,name=items,proto3" json:"items,omitempty"`                                  // transfer multiple tokens for single transfer
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CCTransfer) Reset() {
	*x = CCTransfer{}
	mi := &file_cctranfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCTransfer) ProtoMessage() {}

func (x *CCTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_cctranfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCTransfer.ProtoReflect.Descriptor instead.
func (*CCTransfer) Descriptor() ([]byte, []int) {
	return file_cctranfer_proto_rawDescGZIP(), []int{0}
}

func (x *CCTransfer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CCTransfer) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *CCTransfer) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *CCTransfer) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CCTransfer) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CCTransfer) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CCTransfer) GetForwardDirection() bool {
	if x != nil {
		return x.ForwardDirection
	}
	return false
}

func (x *CCTransfer) GetIsCommit() bool {
	if x != nil {
		return x.IsCommit
	}
	return false
}

func (x *CCTransfer) GetTimeAsNanos() int64 {
	if x != nil {
		return x.TimeAsNanos
	}
	return 0
}

func (x *CCTransfer) GetItems() []*CCTransferItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CCTransfers struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bookmark      string                 `protobuf:"bytes,1,opt,name=bookmark,proto3" json:"bookmark,omitempty"`
	Ccts          []*CCTransfer          `protobuf:"bytes,2,rep,name=ccts,proto3" json:"ccts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCTransfers) Reset() {
	*x = CCTransfers{}
	mi := &file_cctranfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCTransfers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCTransfers) ProtoMessage() {}

func (x *CCTransfers) ProtoReflect() protoreflect.Message {
	mi := &file_cctranfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCTransfers.ProtoReflect.Descriptor instead.
func (*CCTransfers) Descriptor() ([]byte, []int) {
	return file_cctranfer_proto_rawDescGZIP(), []int{1}
}

func (x *CCTransfers) GetBookmark() string {
	if x != nil {
		return x.Bookmark
	}
	return ""
}

func (x *CCTransfers) GetCcts() []*CCTransfer {
	if x != nil {
		return x.Ccts
	}
	return nil
}

type CCTransferItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Amount        []byte                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	User          []byte                 `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Hold          bool                   `protobuf:"varint,4,opt,name=hold,proto3" json:"hold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CCTransferItem) Reset() {
	*x = CCTransferItem{}
	mi := &file_cctranfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CCTransferItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CCTransferItem) ProtoMessage() {}

func (x *CCTransferItem) ProtoReflect() protoreflect.Message {
	mi := &file_cctranfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CCTransferItem.ProtoReflect.Descriptor instead.
func (*CCTransferItem) Descriptor() ([]byte, []int) {
	return file_cctranfer_proto_rawDescGZIP(), []int{2}
}

func (x *CCTransferItem) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CCTransferItem) GetAmount() []byte {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *CCTransferItem) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CCTransferItem) GetHold() bool {
	if x != nil {
		return x.Hold
	}
	return false
}

var File_cctranfer_proto protoreflect.FileDescriptor

const file_cctranfer_proto_rawDesc = "" +
	"\n" +
	"\x0fcctranfer.proto\x12\x05proto\"\x9c\x02\n" +
	"\n" +
	"CCTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\x12\x12\n" +
	"\x04user\x18\x05 \x01(\fR\x04user\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\fR\x06amount\x12+\n" +
	"\x11forward_direction\x18\a \x01(\bR\x10forwardDirection\x12\x1a\n" +
	"\bisCommit\x18\b \x01(\bR\bisCommit\x12\"\n" +
	"\rtime_as_nanos\x18\t \x01(\x03R\vtimeAsNanos\x12+\n" +
	"\x05items\x18\n" +
	" \x03(\v2\x15.proto.CCTransferItemR\x05items\"P\n" +
	"\vCCTransfers\x12\x1a\n" +
	"\bbookmark\x18\x01 \x01(\tR\bbookmark\x12%\n" +
	"\x04ccts\x18\x02 \x03(\v2\x11.proto.CCTransferR\x04ccts\"f\n" +
	"\x0eCCTransferItem\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\fR\x06amount\x12\x12\n" +
	"\x04user\x18\x03 \x01(\fR\x04user\x12\x12\n" +
	"\x04hold\x18\x04 \x01(\bR\x04holdB)Z'github.com/anoideaopen/foundation/protob\x06proto3"

var (
	file_cctranfer_proto_rawDescOnce sync.Once
	file_cctranfer_proto_rawDescData []byte
)

func file_cctranfer_proto_rawDescGZIP() []byte {
	file_cctranfer_proto_rawDescOnce.Do(func() {
		file_cctranfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cctranfer_proto_rawDesc), len(file_cctranfer_proto_rawDesc)))
	})
	return file_cctranfer_proto_rawDescData
}

var file_cctranfer_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cctranfer_proto_goTypes = []any{
	(*CCTransfer)(nil),     // 0: proto.CCTransfer
	(*CCTransfers)(nil),    // 1: proto.CCTransfers
	(*CCTransferItem)(nil), // 2: proto.CCTransferItem
}
var file_cctranfer_proto_depIdxs = []int32{
	2, // 0: proto.CCTransfer.items:type_name -> proto.CCTransferItem
	0, // 1: proto.CCTransfers.ccts:type_name -> proto.CCTransfer
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_cctranfer_proto_init() }
func file_cctranfer_proto_init() {
	if File_cctranfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cctranfer_proto_rawDesc), len(file_cctranfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cctranfer_proto_goTypes,
		DependencyIndexes: file_cctranfer_proto_depIdxs,
		MessageInfos:      file_cctranfer_proto_msgTypes,
	}.Build()
	File_cctranfer_proto = out.File
	file_cctranfer_proto_goTypes = nil
	file_cctranfer_proto_depIdxs = nil
}
