// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: foundation_config.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Config stores all chaincode configuration parameters.
type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *ContractConfig        `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Token         *TokenConfig           `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExtConfig     *anypb.Any             `protobuf:"bytes,3,opt,name=ext_config,json=extConfig,proto3" json:"ext_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_foundation_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_foundation_config_proto_rawDescGZIP(), []int{0}
}

func (x *Config) GetContract() *ContractConfig {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *Config) GetToken() *TokenConfig {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *Config) GetExtConfig() *anypb.Any {
	if x != nil {
		return x.ExtConfig
	}
	return nil
}

// ContractConfig is a configuration for platform base contract.
type ContractConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// symbol is a contract identifier, usually called token ticker.
	Symbol string `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	// ChaincodeOptions stores contract options.
	Options *ChaincodeOptions `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	// robotSKI is the platform robot public key SKI in hex format.
	RobotSKI string `protobuf:"bytes,3,opt,name=robotSKI,proto3" json:"robotSKI,omitempty"`
	// admin is an address of user who can import manipulations with contract.
	Admin *Wallet `protobuf:"bytes,4,opt,name=admin,proto3" json:"admin,omitempty"`
	// tracingCollectorEndpoint - tracing collector endpoint host & port, e.g. "172.23.0.6:4318"
	TracingCollectorEndpoint *CollectorEndpoint `protobuf:"bytes,5,opt,name=tracingCollectorEndpoint,proto3" json:"tracingCollectorEndpoint,omitempty"`
	// maxChannelTransferItems maximum count channel transfer items (token amount) for single transfer operation,
	// if maxChannelTransferItems is 0 will use default value 100
	MaxChannelTransferItems uint32 `protobuf:"varint,6,opt,name=maxChannelTransferItems,proto3" json:"maxChannelTransferItems,omitempty"`
	Acl           *ContractConfigACL `protobuf:"bytes,7,opt,name=acl,proto3" json:"acl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractConfig) Reset() {
	*x = ContractConfig{}
	mi := &file_foundation_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractConfig) ProtoMessage() {}

func (x *ContractConfig) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractConfig.ProtoReflect.Descriptor instead.
func (*ContractConfig) Descriptor() ([]byte, []int) {
	return file_foundation_config_proto_rawDescGZIP(), []int{1}
}

func (x *ContractConfig) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *ContractConfig) GetOptions() *ChaincodeOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *ContractConfig) GetRobotSKI() string {
	if x != nil {
		return x.RobotSKI
	}
	return ""
}

func (x *ContractConfig) GetAdmin() *Wallet {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *ContractConfig) GetTracingCollectorEndpoint() *CollectorEndpoint {
	if x != nil {
		return x.TracingCollectorEndpoint
	}
	return nil
}

func (x *ContractConfig) GetMaxChannelTransferItems() uint32 {
	if x != nil {
		return x.MaxChannelTransferItems
	}
	return 0
}

func (x *ContractConfig) GetAcl() *ContractConfigACL {
	if x != nil {
		return x.Acl
	}
	return nil
}

type ContractConfigACL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelName   string                 `protobuf:"bytes,1,opt,name=channel_name,json=channelName,proto3" json:"channel_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractConfigACL) Reset() {
	*x = ContractConfigACL{}
	mi := &file_foundation_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractConfigACL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractConfigACL) ProtoMessage() {}

func (x *ContractConfigACL) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractConfigACL.ProtoReflect.Descriptor instead.
func (*ContractConfigACL) Descriptor() ([]byte, []int) {
	return file_foundation_config_proto_rawDescGZIP(), []int{2}
}

func (x *ContractConfigACL) GetChannelName() string {
	if x != nil {
		return x.ChannelName
	}
	return ""
}

type CollectorEndpoint struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Endpoint                 string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AuthorizationHeaderKey   string                 `protobuf:"bytes,2,opt,name=authorization_header_key,json=authorizationHeaderKey,proto3" json:"authorization_header_key,omitempty"`
	AuthorizationHeaderValue string                 `protobuf:"bytes,3,opt,name=authorization_header_value,json=authorizationHeaderValue,proto3" json:"authorization_header_value,omitempty"`
	TlsCa                    string                 `protobuf:"bytes,4,opt,name=tls_ca,json=tlsCa,proto3" json:"tls_ca,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CollectorEndpoint) Reset() {
	*x = CollectorEndpoint{}
	mi := &file_foundation_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectorEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectorEndpoint) ProtoMessage() {}

func (x *CollectorEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectorEndpoint.ProtoReflect.Descriptor instead.
func (*CollectorEndpoint) Descriptor() ([]byte, []int) {
	return file_foundation_config_proto_rawDescGZIP(), []int{3}
}

func (x *CollectorEndpoint) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *CollectorEndpoint) GetAuthorizationHeaderKey() string {
	if x != nil {
		return x.AuthorizationHeaderKey
	}
	return ""
}

func (x *CollectorEndpoint) GetAuthorizationHeaderValue() string {
	if x != nil {
		return x.AuthorizationHeaderValue
	}
	return ""
}

func (x *CollectorEndpoint) GetTlsCa() string {
	if x != nil {
		return x.TlsCa
	}
	return ""
}

// ChaincodeOptions stores possible chaincode configuration options.
type ChaincodeOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// disabled_functions stores list of disabled chaincode methods.
	// This methods can't be called.
	DisabledFunctions []string `protobuf:"bytes,1,rep,name=disabled_functions,json=disabledFunctions,proto3" json:"disabled_functions,omitempty"`
	// disable_swaps determines whether swap operations can be performed.
	DisableSwaps bool `protobuf:"varint,2,opt,name=disable_swaps,json=disableSwaps,proto3" json:"disable_swaps,omitempty"`
	// disable_multi_swaps determines whether multi-swap operations can be performed.
	DisableMultiSwaps bool `protobuf:"varint,3,opt,name=disable_multi_swaps,json=disableMultiSwaps,proto3" json:"disable_multi_swaps,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ChaincodeOptions) Reset() {
	*x = ChaincodeOptions{}
	mi := &file_foundation_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChaincodeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChaincodeOptions) ProtoMessage() {}

func (x *ChaincodeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChaincodeOptions.ProtoReflect.Descriptor instead.
func (*ChaincodeOptions) Descriptor() ([]byte, []int) {
	return file_foundation_config_proto_rawDescGZIP(), []int{4}
}

func (x *ChaincodeOptions) GetDisabledFunctions() []string {
	if x != nil {
		return x.DisabledFunctions
	}
	return nil
}

func (x *ChaincodeOptions) GetDisableSwaps() bool {
	if x != nil {
		return x.DisableSwaps
	}
	return false
}

func (x *ChaincodeOptions) GetDisableMultiSwaps() bool {
	if x != nil {
		return x.DisableMultiSwaps
	}
	return false
}

// Wallet stores user specific data.
type Wallet struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// address is a user public key in base58check format.
	Address       string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_foundation_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_foundation_config_proto_rawDescGZIP(), []int{5}
}

func (x *Wallet) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// TokenConfig is a configuration for base token.
type TokenConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is a token name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// decimals is a token's dimension.
	Decimals uint32 `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"`
	// underlying_asset is an asset that backs the token.
	UnderlyingAsset string `protobuf:"bytes,3,opt,name=underlying_asset,json=underlyingAsset,proto3" json:"underlying_asset,omitempty"`
	// issuer is the user which can emit tokens.
	Issuer *Wallet `protobuf:"bytes,4,opt,name=issuer,proto3" json:"issuer,omitempty"`
	// fee_setter is the user which can set and change fees for operations.
	FeeSetter *Wallet `protobuf:"bytes,5,opt,name=fee_setter,json=feeSetter,proto3" json:"fee_setter,omitempty"`
	// fee_address_setter is the user who can set the set address of the commissions manager.
	FeeAddressSetter *Wallet `protobuf:"bytes,6,opt,name=fee_address_setter,json=feeAddressSetter,proto3" json:"fee_address_setter,omitempty"`
	// redeemer is the user who has permission to manage redemption process.
	Redeemer      *Wallet `protobuf:"bytes,7,opt,name=redeemer,proto3" json:"redeemer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenConfig) Reset() {
	*x = TokenConfig{}
	mi := &file_foundation_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenConfig) ProtoMessage() {}

func (x *TokenConfig) ProtoReflect() protoreflect.Message {
	mi := &file_foundation_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenConfig.ProtoReflect.Descriptor instead.
func (*TokenConfig) Descriptor() ([]byte, []int) {
	return file_foundation_config_proto_rawDescGZIP(), []int{6}
}

func (x *TokenConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TokenConfig) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenConfig) GetUnderlyingAsset() string {
	if x != nil {
		return x.UnderlyingAsset
	}
	return ""
}

func (x *TokenConfig) GetIssuer() *Wallet {
	if x != nil {
		return x.Issuer
	}
	return nil
}

func (x *TokenConfig) GetFeeSetter() *Wallet {
	if x != nil {
		return x.FeeSetter
	}
	return nil
}

func (x *TokenConfig) GetFeeAddressSetter() *Wallet {
	if x != nil {
		return x.FeeAddressSetter
	}
	return nil
}

func (x *TokenConfig) GetRedeemer() *Wallet {
	if x != nil {
		return x.Redeemer
	}
	return nil
}

var File_foundation_config_proto protoreflect.FileDescriptor

const file_foundation_config_proto_rawDesc = "" +
	"\n" +
	"\x17foundation_config.proto\x12\x05proto\x1a\x19google/protobuf/any.proto\x1a\x17validate/validate.proto\"\xa6\x01\n" +
	"\x06Config\x12=\n" +
	"\bcontract\x18\x01 \x01(\v2\x15.proto.ContractConfigB\n" +
	"\xfaB\a\x8a\x01\x04\b\x00\x10\x01R\bcontract\x12(\n" +
	"\x05token\x18\x02 \x01(\v2\x12.proto.TokenConfigR\x05token\x123\n" +
	"\n" +
	"ext_config\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\textConfig\"\xa3\x03\n" +
	"\x0eContractConfig\x12M\n" +
	"\x06symbol\x18\x01 \x01(\tB5\xfaB2r02.^[A-Z]+[A-Z0-9]+([-_][A-Z0-9]+(.[A-Z0-9]+)?)?$R\x06symbol\x121\n" +
	"\aoptions\x18\x02 \x01(\v2\x17.proto.ChaincodeOptionsR\aoptions\x12.\n" +
	"\brobotSKI\x18\x03 \x01(\tB\x12\xfaB\x0fr\r2\v^[0-9a-f]+$R\brobotSKI\x12#\n" +
	"\x05admin\x18\x04 \x01(\v2\r.proto.WalletR\x05admin\x12T\n" +
	"\x18tracingCollectorEndpoint\x18\x05 \x01(\v2\x18.proto.CollectorEndpointR\x18tracingCollectorEndpoint\x128\n" +
	"\x17maxChannelTransferItems\x18\x06 \x01(\rR\x17maxChannelTransferItems\x12*\n" +
	"\x03acl\x18\a \x01(\v2\x18.proto.ContractConfigACLR\x03acl\"6\n" +
	"\x11ContractConfigACL\x12!\n" +
	"\fchannel_name\x18\x01 \x01(\tR\vchannelName\"\xbe\x01\n" +
	"\x11CollectorEndpoint\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x128\n" +
	"\x18authorization_header_key\x18\x02 \x01(\tR\x16authorizationHeaderKey\x12<\n" +
	"\x1aauthorization_header_value\x18\x03 \x01(\tR\x18authorizationHeaderValue\x12\x15\n" +
	"\x06tls_ca\x18\x04 \x01(\tR\x05tlsCa\"\x96\x01\n" +
	"\x10ChaincodeOptions\x12-\n" +
	"\x12disabled_functions\x18\x01 \x03(\tR\x11disabledFunctions\x12#\n" +
	"\rdisable_swaps\x18\x02 \x01(\bR\fdisableSwaps\x12.\n" +
	"\x13disable_multi_swaps\x18\x03 \x01(\bR\x11disableMultiSwaps\"B\n" +
	"\x06Wallet\x128\n" +
	"\aaddress\x18\x01 \x01(\tB\x1e\xfaB\x1br\x192\x17^[1-9A-HJ-NP-Za-km-z]+$R\aaddress\"\xaf\x02\n" +
	"\vTokenConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\rR\bdecimals\x12)\n" +
	"\x10underlying_asset\x18\x03 \x01(\tR\x0funderlyingAsset\x12/\n" +
	"\x06issuer\x18\x04 \x01(\v2\r.proto.WalletB\b\xfaB\x05\x8a\x01\x02\x10\x01R\x06issuer\x12,\n" +
	"\n" +
	"fee_setter\x18\x05 \x01(\v2\r.proto.WalletR\tfeeSetter\x12;\n" +
	"\x12fee_address_setter\x18\x06 \x01(\v2\r.proto.WalletR\x10feeAddressSetter\x12)\n" +
	"\bredeemer\x18\a \x01(\v2\r.proto.WalletR\bredeemerB)Z'github.com/anoideaopen/foundation/protob\x06proto3"

var (
	file_foundation_config_proto_rawDescOnce sync.Once
	file_foundation_config_proto_rawDescData []byte
)

func file_foundation_config_proto_rawDescGZIP() []byte {
	file_foundation_config_proto_rawDescOnce.Do(func() {
		file_foundation_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_foundation_config_proto_rawDesc), len(file_foundation_config_proto_rawDesc)))
	})
	return file_foundation_config_proto_rawDescData
}

var file_foundation_config_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_foundation_config_proto_goTypes = []any{
	(*Config)(nil),            // 0: proto.Config
	(*ContractConfig)(nil),    // 1: proto.ContractConfig
	(*ContractConfigACL)(nil), // 2: proto.ContractConfigACL
	(*CollectorEndpoint)(nil), // 3: proto.CollectorEndpoint
	(*ChaincodeOptions)(nil),  // 4: proto.ChaincodeOptions
	(*Wallet)(nil),            // 5: proto.Wallet
	(*TokenConfig)(nil),       // 6: proto.TokenConfig
	(*anypb.Any)(nil),         // 7: google.protobuf.Any
}
var file_foundation_config_proto_depIdxs = []int32{
	1,  // 0: proto.Config.contract:type_name -> proto.ContractConfig
	6,  // 1: proto.Config.token:type_name -> proto.TokenConfig
	7,  // 2: proto.Config.ext_config:type_name -> google.protobuf.Any
	4,  // 3: proto.ContractConfig.options:type_name -> proto.ChaincodeOptions
	5,  // 4: proto.ContractConfig.admin:type_name -> proto.Wallet
	3,  // 5: proto.ContractConfig.tracingCollectorEndpoint:type_name -> proto.CollectorEndpoint
	2,  // 6: proto.ContractConfig.acl:type_name -> proto.ContractConfigACL
	5,  // 7: proto.TokenConfig.issuer:type_name -> proto.Wallet
	5,  // 8: proto.TokenConfig.fee_setter:type_name -> proto.Wallet
	5,  // 9: proto.TokenConfig.fee_address_setter:type_name -> proto.Wallet
	5,  // 10: proto.TokenConfig.redeemer:type_name -> proto.Wallet
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_foundation_config_proto_init() }
func file_foundation_config_proto_init() {
	if File_foundation_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_foundation_config_proto_rawDesc), len(file_foundation_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_foundation_config_proto_goTypes,
		DependencyIndexes: file_foundation_config_proto_depIdxs,
		MessageInfos:      file_foundation_config_proto_msgTypes,
	}.Build()
	File_foundation_config_proto = out.File
	file_foundation_config_proto_goTypes = nil
	file_foundation_config_proto_depIdxs = nil
}
