// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: report.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Report struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FeePublicKey     []byte                 `protobuf:"bytes,1,opt,name=fee_public_key,json=feePublicKey,proto3" json:"fee_public_key,omitempty"`
	ChecksumOrderer  uint64                 `protobuf:"varint,2,opt,name=checksum_orderer,json=checksumOrderer,proto3" json:"checksum_orderer,omitempty"`
	ChecksumEndorser uint64                 `protobuf:"varint,3,opt,name=checksum_endorser,json=checksumEndorser,proto3" json:"checksum_endorser,omitempty"`
	Stats            []*Stat                `protobuf:"bytes,4,rep,name=stats,proto3" json:"stats,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

func (x *Report) GetFeePublicKey() []byte {
	if x != nil {
		return x.FeePublicKey
	}
	return nil
}

func (x *Report) GetChecksumOrderer() uint64 {
	if x != nil {
		return x.ChecksumOrderer
	}
	return 0
}

func (x *Report) GetChecksumEndorser() uint64 {
	if x != nil {
		return x.ChecksumEndorser
	}
	return 0
}

func (x *Report) GetStats() []*Stat {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Stat struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CertOwner      string                 `protobuf:"bytes,1,opt,name=cert_owner,json=certOwner,proto3" json:"cert_owner,omitempty"`
	PointsEndorser uint64                 `protobuf:"varint,2,opt,name=points_endorser,json=pointsEndorser,proto3" json:"points_endorser,omitempty"`
	PointsOrderer  uint64                 `protobuf:"varint,3,opt,name=points_orderer,json=pointsOrderer,proto3" json:"points_orderer,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Stat) Reset() {
	*x = Stat{}
	mi := &file_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stat) ProtoMessage() {}

func (x *Stat) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stat.ProtoReflect.Descriptor instead.
func (*Stat) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

func (x *Stat) GetCertOwner() string {
	if x != nil {
		return x.CertOwner
	}
	return ""
}

func (x *Stat) GetPointsEndorser() uint64 {
	if x != nil {
		return x.PointsEndorser
	}
	return 0
}

func (x *Stat) GetPointsOrderer() uint64 {
	if x != nil {
		return x.PointsOrderer
	}
	return 0
}

type HeadInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Heads         []*Head                `protobuf:"bytes,1,rep,name=heads,proto3" json:"heads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeadInfo) Reset() {
	*x = HeadInfo{}
	mi := &file_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadInfo) ProtoMessage() {}

func (x *HeadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadInfo.ProtoReflect.Descriptor instead.
func (*HeadInfo) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{2}
}

func (x *HeadInfo) GetHeads() []*Head {
	if x != nil {
		return x.Heads
	}
	return nil
}

type Head struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	BlockNum      uint64                 `protobuf:"varint,2,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Head) Reset() {
	*x = Head{}
	mi := &file_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{3}
}

func (x *Head) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Head) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

var File_report_proto protoreflect.FileDescriptor

const file_report_proto_rawDesc = "" +
	"\n" +
	"\freport.proto\x12\x05proto\"\xa9\x01\n" +
	"\x06Report\x12$\n" +
	"\x0efee_public_key\x18\x01 \x01(\fR\ffeePublicKey\x12)\n" +
	"\x10checksum_orderer\x18\x02 \x01(\x04R\x0fchecksumOrderer\x12+\n" +
	"\x11checksum_endorser\x18\x03 \x01(\x04R\x10checksumEndorser\x12!\n" +
	"\x05stats\x18\x04 \x03(\v2\v.proto.StatR\x05stats\"u\n" +
	"\x04Stat\x12\x1d\n" +
	"\n" +
	"cert_owner\x18\x01 \x01(\tR\tcertOwner\x12'\n" +
	"\x0fpoints_endorser\x18\x02 \x01(\x04R\x0epointsEndorser\x12%\n" +
	"\x0epoints_orderer\x18\x03 \x01(\x04R\rpointsOrderer\"-\n" +
	"\bHeadInfo\x12!\n" +
	"\x05heads\x18\x01 \x03(\v2\v.proto.HeadR\x05heads\"9\n" +
	"\x04Head\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tblock_num\x18\x02 \x01(\x04R\bblockNumB)Z'github.com/anoideaopen/foundation/protob\x06proto3"

var (
	file_report_proto_rawDescOnce sync.Once
	file_report_proto_rawDescData []byte
)

func file_report_proto_rawDescGZIP() []byte {
	file_report_proto_rawDescOnce.Do(func() {
		file_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)))
	})
	return file_report_proto_rawDescData
}

var file_report_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_report_proto_goTypes = []any{
	(*Report)(nil),   // 0: proto.Report
	(*Stat)(nil),     // 1: proto.Stat
	(*HeadInfo)(nil), // 2: proto.HeadInfo
	(*Head)(nil),     // 3: proto.Head
}
var file_report_proto_depIdxs = []int32{
	1, // 0: proto.Report.stats:type_name -> proto.Stat
	3, // 1: proto.HeadInfo.heads:type_name -> proto.Head
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_report_proto_init() }
func file_report_proto_init() {
	if File_report_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_report_proto_goTypes,
		DependencyIndexes: file_report_proto_depIdxs,
		MessageInfos:      file_report_proto_msgTypes,
	}.Build()
	File_report_proto = out.File
	file_report_proto_goTypes = nil
	file_report_proto_depIdxs = nil
}
