// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: transfer_request.proto

package proto

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum representing the types of documents.
type DocumentType int32

const (
	DocumentType_DOCUMENT_TYPE_UNSPECIFIED DocumentType = 0 // Unspecified document type
	DocumentType_DOCUMENT_TYPE_LEGAL       DocumentType = 1 // Record Sheet of the Unified State Register of Legal Entities (EGRUL)
	DocumentType_DOCUMENT_TYPE_INHERITANCE DocumentType = 2 // Certificate of Inheritance
	DocumentType_DOCUMENT_TYPE_JUDGMENT    DocumentType = 3 // Writ of Execution
)

// Enum value maps for DocumentType.
var (
	DocumentType_name = map[int32]string{
		0: "DOCUMENT_TYPE_UNSPECIFIED",
		1: "DOCUMENT_TYPE_LEGAL",
		2: "DOCUMENT_TYPE_INHERITANCE",
		3: "DOCUMENT_TYPE_JUDGMENT",
	}
	DocumentType_value = map[string]int32{
		"DOCUMENT_TYPE_UNSPECIFIED": 0,
		"DOCUMENT_TYPE_LEGAL":       1,
		"DOCUMENT_TYPE_INHERITANCE": 2,
		"DOCUMENT_TYPE_JUDGMENT":    3,
	}
)

func (x DocumentType) Enum() *DocumentType {
	p := new(DocumentType)
	*p = x
	return p
}

func (x DocumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_transfer_request_proto_enumTypes[0].Descriptor()
}

func (DocumentType) Type() protoreflect.EnumType {
	return &file_transfer_request_proto_enumTypes[0]
}

func (x DocumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentType.Descriptor instead.
func (DocumentType) EnumDescriptor() ([]byte, []int) {
	return file_transfer_request_proto_rawDescGZIP(), []int{0}
}

// Enum representing the basis for the transfer.
type TransferBasis int32

const (
	TransferBasis_TRANSFER_BASIS_UNSPECIFIED    TransferBasis = 0 // Unspecified basis
	TransferBasis_TRANSFER_BASIS_REORGANIZATION TransferBasis = 1 // Reorganization of a legal entity
	TransferBasis_TRANSFER_BASIS_INHERITANCE    TransferBasis = 2 // Inheritance
	TransferBasis_TRANSFER_BASIS_COURT_DECISION TransferBasis = 3 // Court decision
)

// Enum value maps for TransferBasis.
var (
	TransferBasis_name = map[int32]string{
		0: "TRANSFER_BASIS_UNSPECIFIED",
		1: "TRANSFER_BASIS_REORGANIZATION",
		2: "TRANSFER_BASIS_INHERITANCE",
		3: "TRANSFER_BASIS_COURT_DECISION",
	}
	TransferBasis_value = map[string]int32{
		"TRANSFER_BASIS_UNSPECIFIED":    0,
		"TRANSFER_BASIS_REORGANIZATION": 1,
		"TRANSFER_BASIS_INHERITANCE":    2,
		"TRANSFER_BASIS_COURT_DECISION": 3,
	}
)

func (x TransferBasis) Enum() *TransferBasis {
	p := new(TransferBasis)
	*p = x
	return p
}

func (x TransferBasis) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransferBasis) Descriptor() protoreflect.EnumDescriptor {
	return file_transfer_request_proto_enumTypes[1].Descriptor()
}

func (TransferBasis) Type() protoreflect.EnumType {
	return &file_transfer_request_proto_enumTypes[1]
}

func (x TransferBasis) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransferBasis.Descriptor instead.
func (TransferBasis) EnumDescriptor() ([]byte, []int) {
	return file_transfer_request_proto_rawDescGZIP(), []int{1}
}

// Enum representing the types of balances.
type BalanceType int32

const (
	BalanceType_BALANCE_TYPE_UNSPECIFIED           BalanceType = 0  // Unspecified balance type
	BalanceType_BALANCE_TYPE_TOKEN                 BalanceType = 43 // 0x2b
	BalanceType_BALANCE_TYPE_TOKEN_EXTERNAL_LOCKED BalanceType = 50 // 0x32
)

// Enum value maps for BalanceType.
var (
	BalanceType_name = map[int32]string{
		0:  "BALANCE_TYPE_UNSPECIFIED",
		43: "BALANCE_TYPE_TOKEN",
		50: "BALANCE_TYPE_TOKEN_EXTERNAL_LOCKED",
	}
	BalanceType_value = map[string]int32{
		"BALANCE_TYPE_UNSPECIFIED":           0,
		"BALANCE_TYPE_TOKEN":                 43,
		"BALANCE_TYPE_TOKEN_EXTERNAL_LOCKED": 50,
	}
)

func (x BalanceType) Enum() *BalanceType {
	p := new(BalanceType)
	*p = x
	return p
}

func (x BalanceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BalanceType) Descriptor() protoreflect.EnumDescriptor {
	return file_transfer_request_proto_enumTypes[2].Descriptor()
}

func (BalanceType) Type() protoreflect.EnumType {
	return &file_transfer_request_proto_enumTypes[2]
}

func (x BalanceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BalanceType.Descriptor instead.
func (BalanceType) EnumDescriptor() ([]byte, []int) {
	return file_transfer_request_proto_rawDescGZIP(), []int{2}
}

// Message representing a transfer request.
type TransferRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Transfer request ID
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Basis for the transfer
	Basis TransferBasis `protobuf:"varint,2,opt,name=basis,proto3,enum=proto.TransferBasis" json:"basis,omitempty"`
	// Administrator ID
	AdministratorId string `protobuf:"bytes,3,opt,name=administrator_id,json=administratorId,proto3" json:"administrator_id,omitempty"`
	// Document type
	DocumentType DocumentType `protobuf:"varint,4,opt,name=document_type,json=documentType,proto3,enum=proto.DocumentType" json:"document_type,omitempty"`
	// Document number
	DocumentNumber string `protobuf:"bytes,5,opt,name=document_number,json=documentNumber,proto3" json:"document_number,omitempty"`
	// Document date
	DocumentDate *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=document_date,json=documentDate,proto3" json:"document_date,omitempty"`
	// Hashes of attached documents
	DocumentHashes []string `protobuf:"bytes,7,rep,name=document_hashes,json=documentHashes,proto3" json:"document_hashes,omitempty"`
	// Address from which the transfer is made
	FromAddress string `protobuf:"bytes,8,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	// Address to which the transfer is made
	ToAddress string `protobuf:"bytes,9,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// Token being transferred
	Token string `protobuf:"bytes,10,opt,name=token,proto3" json:"token,omitempty"`
	// Amount being transferred
	Amount string `protobuf:"bytes,11,opt,name=amount,proto3" json:"amount,omitempty"`
	// Reason for the transfer
	Reason string `protobuf:"bytes,12,opt,name=reason,proto3" json:"reason,omitempty"`
	// Balance type from which the transfer is made
	BalanceType BalanceType `protobuf:"varint,13,opt,name=balance_type,json=balanceType,proto3,enum=proto.BalanceType" json:"balance_type,omitempty"`
	// Optional additional information
	AdditionalInfo *anypb.Any `protobuf:"bytes,15,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransferRequest) Reset() {
	*x = TransferRequest{}
	mi := &file_transfer_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferRequest) ProtoMessage() {}

func (x *TransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transfer_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferRequest.ProtoReflect.Descriptor instead.
func (*TransferRequest) Descriptor() ([]byte, []int) {
	return file_transfer_request_proto_rawDescGZIP(), []int{0}
}

func (x *TransferRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *TransferRequest) GetBasis() TransferBasis {
	if x != nil {
		return x.Basis
	}
	return TransferBasis_TRANSFER_BASIS_UNSPECIFIED
}

func (x *TransferRequest) GetAdministratorId() string {
	if x != nil {
		return x.AdministratorId
	}
	return ""
}

func (x *TransferRequest) GetDocumentType() DocumentType {
	if x != nil {
		return x.DocumentType
	}
	return DocumentType_DOCUMENT_TYPE_UNSPECIFIED
}

func (x *TransferRequest) GetDocumentNumber() string {
	if x != nil {
		return x.DocumentNumber
	}
	return ""
}

func (x *TransferRequest) GetDocumentDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DocumentDate
	}
	return nil
}

func (x *TransferRequest) GetDocumentHashes() []string {
	if x != nil {
		return x.DocumentHashes
	}
	return nil
}

func (x *TransferRequest) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *TransferRequest) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *TransferRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TransferRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TransferRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TransferRequest) GetBalanceType() BalanceType {
	if x != nil {
		return x.BalanceType
	}
	return BalanceType_BALANCE_TYPE_UNSPECIFIED
}

func (x *TransferRequest) GetAdditionalInfo() *anypb.Any {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

var File_transfer_request_proto protoreflect.FileDescriptor

const file_transfer_request_proto_rawDesc = "" +
	"\n" +
	"\x16transfer_request.proto\x12\x05proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xe8\x05\n" +
	"\x0fTransferRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x124\n" +
	"\x05basis\x18\x02 \x01(\x0e2\x14.proto.TransferBasisB\b\xfaB\x05\x82\x01\x02\x10\x01R\x05basis\x122\n" +
	"\x10administrator_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0fadministratorId\x12B\n" +
	"\rdocument_type\x18\x04 \x01(\x0e2\x13.proto.DocumentTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\fdocumentType\x120\n" +
	"\x0fdocument_number\x18\x05 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x0edocumentNumber\x12I\n" +
	"\rdocument_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\b\xfaB\x05\xb2\x01\x02\b\x01R\fdocumentDate\x121\n" +
	"\x0fdocument_hashes\x18\a \x03(\tB\b\xfaB\x05\x92\x01\x02\b\x01R\x0edocumentHashes\x12A\n" +
	"\ffrom_address\x18\b \x01(\tB\x1e\xfaB\x1br\x192\x17^[1-9A-HJ-NP-Za-km-z]+$R\vfromAddress\x12=\n" +
	"\n" +
	"to_address\x18\t \x01(\tB\x1e\xfaB\x1br\x192\x17^[1-9A-HJ-NP-Za-km-z]+$R\ttoAddress\x12\x14\n" +
	"\x05token\x18\n" +
	" \x01(\tR\x05token\x12\x1f\n" +
	"\x06amount\x18\v \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06amount\x12\x1f\n" +
	"\x06reason\x18\f \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x06reason\x12?\n" +
	"\fbalance_type\x18\r \x01(\x0e2\x12.proto.BalanceTypeB\b\xfaB\x05\x82\x01\x02\x10\x01R\vbalanceType\x12=\n" +
	"\x0fadditional_info\x18\x0f \x01(\v2\x14.google.protobuf.AnyR\x0eadditionalInfo*\x81\x01\n" +
	"\fDocumentType\x12\x1d\n" +
	"\x19DOCUMENT_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13DOCUMENT_TYPE_LEGAL\x10\x01\x12\x1d\n" +
	"\x19DOCUMENT_TYPE_INHERITANCE\x10\x02\x12\x1a\n" +
	"\x16DOCUMENT_TYPE_JUDGMENT\x10\x03*\x95\x01\n" +
	"\rTransferBasis\x12\x1e\n" +
	"\x1aTRANSFER_BASIS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dTRANSFER_BASIS_REORGANIZATION\x10\x01\x12\x1e\n" +
	"\x1aTRANSFER_BASIS_INHERITANCE\x10\x02\x12!\n" +
	"\x1dTRANSFER_BASIS_COURT_DECISION\x10\x03*k\n" +
	"\vBalanceType\x12\x1c\n" +
	"\x18BALANCE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BALANCE_TYPE_TOKEN\x10+\x12&\n" +
	"\"BALANCE_TYPE_TOKEN_EXTERNAL_LOCKED\x102B)Z'github.com/anoideaopen/foundation/protob\x06proto3"

var (
	file_transfer_request_proto_rawDescOnce sync.Once
	file_transfer_request_proto_rawDescData []byte
)

func file_transfer_request_proto_rawDescGZIP() []byte {
	file_transfer_request_proto_rawDescOnce.Do(func() {
		file_transfer_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transfer_request_proto_rawDesc), len(file_transfer_request_proto_rawDesc)))
	})
	return file_transfer_request_proto_rawDescData
}

var file_transfer_request_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_transfer_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transfer_request_proto_goTypes = []any{
	(DocumentType)(0),             // 0: proto.DocumentType
	(TransferBasis)(0),            // 1: proto.TransferBasis
	(BalanceType)(0),              // 2: proto.BalanceType
	(*TransferRequest)(nil),       // 3: proto.TransferRequest
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*anypb.Any)(nil),             // 5: google.protobuf.Any
}
var file_transfer_request_proto_depIdxs = []int32{
	1, // 0: proto.TransferRequest.basis:type_name -> proto.TransferBasis
	0, // 1: proto.TransferRequest.document_type:type_name -> proto.DocumentType
	4, // 2: proto.TransferRequest.document_date:type_name -> google.protobuf.Timestamp
	2, // 3: proto.TransferRequest.balance_type:type_name -> proto.BalanceType
	5, // 4: proto.TransferRequest.additional_info:type_name -> google.protobuf.Any
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_transfer_request_proto_init() }
func file_transfer_request_proto_init() {
	if File_transfer_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transfer_request_proto_rawDesc), len(file_transfer_request_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transfer_request_proto_goTypes,
		DependencyIndexes: file_transfer_request_proto_depIdxs,
		EnumInfos:         file_transfer_request_proto_enumTypes,
		MessageInfos:      file_transfer_request_proto_msgTypes,
	}.Build()
	File_transfer_request_proto = out.File
	file_transfer_request_proto_goTypes = nil
	file_transfer_request_proto_depIdxs = nil
}
